#!/bin/bash
filename=$(basename "$1")
extension="${filename##*.}"
filename="${filename%.*}"
inputfile=$1
outputfile="$filename.mp4"
ffmpeg -y -i "$inputfile" -acodec aac -strict -2 -ab 160000 -s 1024x768 -vcodec libx264 -b 1200k -threads 0 -f mp4 "$outputfile"
