#!/usr/bin/env ruby
require 'logger'
require 'socket'
require 'open-uri'

module PC
  MAC_ADDRESS = '10:C3:7B:6E:8A:A4' unless const_defined?(:MAC_ADDRESS)
  IP          = '192.168.254.40'    unless const_defined?(:IP)

  class Service
    # requires SleepOnLan utility to be running
    def sleep(*args)
      result = open("http://#{PC::IP}:7760/suspend").read
      puts result
    end

    def wake(*args)
      begin
        preamble = "\xFF\xFF\xFF\xFF\xFF\xFF"
        mac  = PC::MAC_ADDRESS
        data = preamble + (
          mac.split(':').map { |e| e.hex.chr }.join * 16
        )

        puts("Wake-On-Lan packet sent to MAC address " + mac)

        socket = UDPSocket.new
        socket.setsockopt(Socket::SOL_SOCKET, Socket::SO_BROADCAST, true)
        socket.send(data, 0, '<broadcast>', 9)
      end
    end
  end

  def self.invoke!(command, arguments)
    service = PC::Service.new

    valid_commands = %w(sleep wake)

    case command
    when *valid_commands
      service.send(command)
    else
      puts "Unknown command: #{command} #{arguments.inspect}"
    end
  end
end

PC.invoke!(ARGV.shift, ARGV.dup)
